# Generated by Django 3.1.2 on 2020-10-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('x', models.DecimalField(decimal_places=2, default=40.99, max_digits=100)),
                ('t', models.FileField(default='', upload_to='covers/')),
                ('img', models.ImageField(default='', upload_to='covers/')),
            ],
        ),
    ]
